db_root: "/data-nvme"
run: 2023_03
processing:
  #algorithm:
  #  !FirstPeak
  #  threshold: 15
  #  left: 8
  # uncomment to use trapezoid filter
  algorithm:
    !Trapezoid
    left: 6
    center: 15
    right: 6
    treshold: 27
    min_length: 10
    reset_detection:
      window: 10
      treshold: 800
      size: 110
  convert_to_kev: true
post_processing:
  merge_close_events: true
groups:
  Tritium_3:
    1:
      exclude:
        - "p0(30s)(HV1=14000)"
    2:
    3:
monitor: "/data-nvme/monitor-2023-03.json"


